jbrowse add-track --out /Users/colin/ucscResults2 --trackId phyloP447wayBW  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP447way/hg38.phyloP447way.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovAdiposeSubcutaneous  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-NFK9-0326-SM-3MJGV.Adipose_Subcutaneous.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId genetiSureCytoCghSnp  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snpCnvArrays/agilent/hg38.GenetiSure_Cyto_CGH+SNP_Microarray_4x180K_085591_D_BED_20200302.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId allCancer  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/gdcCancer.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap24Pos  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k24.C2T-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinGenHaplo  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/clinGen/clinGenHaplo.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinvarMain  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/clinvar/clinvarMain.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp153Common  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp153Common.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp155Common  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155Common.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasC2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasC2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId crossTissueMapsTissueCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/crossTissueMaps/tissue_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_1000g  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_1000g.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_conflict_pathogenic  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/conflict_pathogenic.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dgvMerged  https://hgdownload.soe.ucsc.edu/gbdb/hg38/dgv/dgvMerged.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId encodeCcreCombined  https://hgdownload.soe.ucsc.edu/gbdb/hg38/encode3/ccre/encodeCcreCombined.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId epdNewPromoter  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/epdNewHuman006.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId knownGene  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gencode/gencodeV44.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pliByGene  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/pliByGene.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerRegElementsDoubleElite  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerRegElementsDoubleElite.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexEqtlCaviar  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/eQtl/gtexCaviar.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId xGen_Research_Probes_V1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/xgen-exome-research-panel-probes-hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId jarvis  https://hgdownload.soe.ucsc.edu/gbdb/hg38/jarvis/jarvis.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId jaspar2024  https://hgdownload.soe.ucsc.edu/gbdb/hg38/jaspar/JASPAR2024.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lovdShort  https://hgdownload.soe.ucsc.edu/gbdb/hg38/lovd/lovd.hg38.short.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId revelA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/revel/a.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/a.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId panelAppCNVs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/panelApp/cnv.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pHaplo  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dosageSensitivityCollins2022/pHaploDosageSensitivity.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recombAvg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recombAvg.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId miRnaAtlasSample1BarChart  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/miRnaAtlasSample1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasR4PvalA2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasR4.A2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId snpediaAll  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/snpediaAll.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipAliSwissprot  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipAliSwissprot.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId comments  https://hgdownload.soe.ucsc.edu/gbdb/hg38/problematic/comments.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap24  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k24.Unique.Mappability.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ACC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/ACC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovAdiposeVisceralOmentum  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-14BMU-0626-SM-73KZ6.Adipose_Visceral_Omentum.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId genetiSureCytoCgh4x180  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snpCnvArrays/agilent/hg38.GenetiSure_Cyto_CGH_Microarray_4x180K_085589_D_BED_20200302.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap36Pos  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k36.C2T-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinGenTriplo  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/clinGen/clinGenTriplo.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinvarCnv  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/clinvar/clinvarCnv.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp155ClinVar  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155ClinVar.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId crossTissueMapsFullDetails  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/crossTissueMaps/facet_detailed.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp153ClinVar  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp153ClinVar.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_african  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_african.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dgvSupporting  https://hgdownload.soe.ucsc.edu/gbdb/hg38/dgv/dgvSupporting.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId encBlacklist  https://hgdownload.soe.ucsc.edu/gbdb/hg38/problematic/encBlacklist.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId epdNewPromoterNonCoding  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/epdNewHumanNc001.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId missenseByGene  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/missenseByGene.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerGenesDoubleElite  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerGenesTssDoubleElite.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gnomadGenomesVariantsV3_1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/v3.1/variants/genomes.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gnomadGenomesVariantsV3_1_1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/v3.1.1/genomes.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexEqtlDapg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/eQtl/gtexDapg.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hmc  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hmc/hmc.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasB2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasB2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasR4PvalB2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasR4.B2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId xGen_Research_Targets_V1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/xgen-exome-research-panel-targets-hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId jaspar2022  https://hgdownload.soe.ucsc.edu/gbdb/hg38/jaspar/JASPAR2022.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lovdLong  https://hgdownload.soe.ucsc.edu/gbdb/hg38/lovd/lovd.hg38.long.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId revelC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/revel/c.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/c.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId panelAppGenes  https://hgdownload.soe.ucsc.edu/gbdb/hg38/panelApp/genes.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pTriplo  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dosageSensitivityCollins2022/pTriploDosageSensitivity.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recombPat  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recombPat.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId miRnaAtlasSample2BarChart  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/miRnaAtlasSample2.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pliByTranscript  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/pliByTranscript.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pliByTranscriptV4  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/pliByTranscript.v4.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId missenseByTranscript  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/missenseByTranscript.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId missenseByTranscriptV4  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/pLI/missenseByTranscript.v4.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipAliTrembl  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipAliTrembl.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap36  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k36.Unique.Mappability.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidMuts  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidMuts/covidMuts.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovAdrenalGland  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Y5LM-0126-SM-4VBRL.Adrenal_Gland.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId genetiSureCytoCghSnp8x60  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snpCnvArrays/agilent/hg38.GenetiSure_Cyto_CGH_Microarray_8x60K_085590_D_BED_20200302.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap50Pos  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.C2T-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId BLCA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/BLCA.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinGenGeneDisease  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/clinGen/clinGenGeneDisease.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp153Mult  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp153Mult.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_global  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_global.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerInteractionsDoubleElite  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerInteractionsDoubleElite.v2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId grcExclusions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/problematic/grcExclusions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexImmuneAtlasFullDetails  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/gtexImmuneAtlas/facet_detailed_class.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId xGen_Research_Probes_V2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/xgen-exome-research-panel-v2-probes-hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId jaspar2020  https://hgdownload.soe.ucsc.edu/gbdb/hg38/jaspar/JASPAR2020.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp155Mult  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155Mult.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId revelG  https://hgdownload.soe.ucsc.edu/gbdb/hg38/revel/g.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddG  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/g.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId panelAppTandRep  https://hgdownload.soe.ucsc.edu/gbdb/hg38/panelApp/tandRep.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recombMat  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recombMat.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipLocSignal  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipLocSignal.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId giabSv  https://hgdownload.soe.ucsc.edu/gbdb/hg38/giab/structuralVariants/giabSv.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasR4PvalC1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasR4.C1.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap50  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.Unique.Mappability.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId phyloP447wayLRT  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP447way/hg38.phyloP447wayLRT.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId phyloP470wayBW  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP470way/hg38.phyloP470way.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId covidHgiGwasR4PvalC2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/covidHgiGwas/covidHgiGwasR4.C2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp153  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp153.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp155  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovArteryAorta  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-WYVS-0426-SM-4ONDL.Artery_Aorta.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId phyloP241wayBW  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/cactus241way/cactus241way.phyloP.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap100Pos  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k100.C2T-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId BRCA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/BRCA.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_decipher  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_decipher.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipLocExtra  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipLocExtra.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerClusteredInteractionsDoubleElite  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerInteractionsDoubleElite.v2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId highReproRegions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/problematic/highRepro/highRepro.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId xGen_Research_Targets_V2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/xgen-exome-research-panel-v2-targets-hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId snpArrayIllumina450k  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/illumina/illumina450K.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipInterest  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipInterest.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId jaspar2018  https://hgdownload.soe.ucsc.edu/gbdb/hg38/jaspar/JASPAR2018.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId revelT  https://hgdownload.soe.ucsc.edu/gbdb/hg38/revel/t.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddT  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/t.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recombEvents  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/events.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ncbiRefSeqOther  https://hgdownload.soe.ucsc.edu/gbdb/hg38/ncbiRefSeq/ncbiRefSeqOther.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap100  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k100.Unique.Mappability.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovArteryCoronary  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1GMR3-0626-SM-9WYT3.Artery_Coronary.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap24Neg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k24.G2A-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId CESC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/CESC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_european  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_european.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerRegElements  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerRegElementsAll.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId snpArrayIllumina850k  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/illumina/epic850K.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId KAPA_HyperExome_hg38_capture_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/KAPA_HyperExome_hg38_capture_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp153BadCoords  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp153BadCoords.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbSnp155BadCoords  https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155BadCoords.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId multiz470way  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz470way/multiz470way.bigMaf
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recombDnm  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recombDenovo.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId revelOverlaps  https://hgdownload.soe.ucsc.edu/gbdb/hg38/revel/overlap.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipLocTransMemb  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipLocTransMemb.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap24Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k24.Umap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovArteryTibial  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-XPT6-2226-SM-4B66R.Artery_Tibial.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap36Neg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k36.G2A-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId CHOL  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/CHOL.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipLocCytopl  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipLocCytopl.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId snpArrayCytoSnp850k  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cytoSnp/cytoSnp850k.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dbVar_common_gnomad  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/dbVar/common_gnomad.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerGenes  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerGenesTssAll.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId KAPA_HyperExome_hg38_primary_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/KAPA_HyperExome_hg38_primary_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId recomb1000GAvg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recomb1000GAvg.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ncbiRefSeqGenomicDiff  https://hgdownload.soe.ucsc.edu/gbdb/hg38/ncbiRefSeq/ncbiRefSeqGenomicDiff.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap36Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k36.Umap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId affyCytoScanHD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/genotypeArrays/affyCytoScanHD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap100Neg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k100.G2A-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap50Neg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.G2A-Converted.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBladder  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-S3XE-1226-SM-4AD4L.Bladder.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipChain  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipChain.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId COAD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/COAD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerInteractions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerInteractionsAll.v2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SeqCap-EZ_MedExome_hg38_capture_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/SeqCap_EZ_MedExome_hg38_capture_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap50Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.Umap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainAmygdala  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-T5JC-0011-R4A-SM-32PLT.Brain_Amygdala.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId phastCons470way  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons470way/hg38.phastCons470way.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipDisulfBond  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipDisulfBond.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId DLBC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/DLBC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipDomain  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipDomain.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneHancerClusteredInteractions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneHancer/geneHancerInteractionsAll.v2.hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SeqCap-EZ_MedExome_hg19_empirical_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/SeqCap_EZ_MedExome_hg38_empirical_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId umap100Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k100.Umap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId phastConsElements470way  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons470way/hg38.phastConsElements470way.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipModif  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipModif.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap24Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k24.Bismap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainAnteriorcingulatecortexBA24  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-14PN4-0011-R3b-SM-686ZU.Brain_Anterior_cingulate_cortex_BA24.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ESCA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/ESCA.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SeqCap-EZ_MedExomePlusMito_hg19_capture_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/SeqCap_EZ_MedExomePlusMito_hg38_capture_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap36Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k36.Bismap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainCaudatebasalganglia  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1HGF4-0011-R5b-SM-CM2ST.Brain_Caudate_basal_ganglia.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId GBM  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/GBM.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gnomadConstraint  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/mutConstraint/mutConstraint.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipMut  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipMut.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SeqCap-EZ_MedExomePlusMito_hg19_empirical_targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/SeqCap_EZ_MedExomePlusMito_hg38_empirical_targets.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId transMapEnsemblV5  https://hgdownload.soe.ucsc.edu/gbdb/hg38/transMap/V5/hg38.ensembl.transMapV5.bigPsl
jbrowse add-track --out /Users/colin/ucscResults2 --trackId transMapRefSeqV5  https://hgdownload.soe.ucsc.edu/gbdb/hg38/transMap/V5/hg38.refseq.transMapV5.bigPsl
jbrowse add-track --out /Users/colin/ucscResults2 --trackId transMapRnaV5  https://hgdownload.soe.ucsc.edu/gbdb/hg38/transMap/V5/hg38.rna.transMapV5.bigPsl
jbrowse add-track --out /Users/colin/ucscResults2 --trackId transMapEstV5  https://hgdownload.soe.ucsc.edu/gbdb/hg38/transMap/V5/hg38.est.transMapV5.bigPsl
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ukbDepletion  https://hgdownload.soe.ucsc.edu/gbdb/hg38/ukbDepletion/ukbDepletion.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap50Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.Bismap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainCerebellum  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-145MH-2926-SM-5Q5D2.Brain_Cerebellum.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId HNSC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/HNSC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipOther  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipOther.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipStruct  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipStruct.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_Clinical_Research_V2_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S30409818_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bismap100Quantitative  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k100.Bismap.MultiTrackMappability.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainCerebellarHemisphere  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-13X6J-0011-R11a-SM-5P9HE.Brain_Cerebellar_Hemisphere.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipRepeat  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipRepeat.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_Clinical_Research_V2_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S30409818_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainCortex  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-UTHO-3026-SM-3GAFB.Brain_Cortex.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId KIRC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/KIRC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId unipConflict  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipConflict.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_Focused_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07084713_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainFrontalCortexBA9  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-T5JC-0011-R10A-SM-32PM2.Brain_Frontal_Cortex_BA9.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId KIRP  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/KIRP.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_Focused_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07084713_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainHippocampus  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1HSKV-0011-R1b-SM-CMKH7.Brain_Hippocampus.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId LAML  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/LAML.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V4_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S04380110_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainHypothalamus  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-T5JC-0011-R8A-SM-32PLM.Brain_Hypothalamus.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId LGG  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/LGG.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V4_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S04380110_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainNucleusaccumbensbasalganglia  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-14BIN-0011-R6a-SM-5S2RH.Brain_Nucleus_accumbens_basal_ganglia.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId LIHC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/LIHC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V5_UTRs_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S04380219_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainPutamenbasalganglia  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1HFI6-0011-R7b-SM-CM2SS.Brain_Putamen_basal_ganglia.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId LUAD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/LUAD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V5_UTRs_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S04380219_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainSpinalcordcervicalc-1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-YFC4-0011-R9a-SM-4SOK4.Brain_Spinal_cord_cervical_c-1.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId LUSC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/LUSC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_UTRs_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604624_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBrainSubstantianigra  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Z93S-0011-R2a-SM-4RGNG.Brain_Substantia_nigra.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId MESO  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/MESO.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604514_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovBreastMammaryTissue  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-ZT9W-2026-SM-51MRA.Breast_Mammary_Tissue.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId OV  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/OV.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604514_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovCellsEBV-transformedlymphocytes  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1122O-0003-SM-5Q5DL.Cells_EBV-transformed_lymphocytes.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId PAAD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/PAAD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_COSMIC_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604715_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovCellsCulturedfibroblasts  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-117XS-0008-SM-5Q5DQ.Cells_Cultured_fibroblasts.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId PCPG  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/PCPG.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_COSMIC_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604715_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovCervixEctocervix  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-S341-1126-SM-4AD6T.Cervix_Ectocervix.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId PRAD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/PRAD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V6_UTRs_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S07604624_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovCervixEndocervix  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-ZPIC-1326-SM-DO91Y.Cervix_Endocervix.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId READ  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/READ.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V7_Covered  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S31285117_Covered.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovColonSigmoid  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1KXAM-1926-SM-D3LAG.Colon_Sigmoid.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SARC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/SARC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Agilent_Human_Exon_V7_Regions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/S31285117_Regions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovColonTransverse  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1IDJC-1326-SM-CL53H.Colon_Transverse.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId SKCM  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/SKCM.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Twist_Comp_Exome_Target  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/Twist_ComprehensiveExome_targets_hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovEsophagusGastroesophagealJunction  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1I1GU-1226-SM-A9SKT.Esophagus_Gastroesophageal_Junction.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId STAD  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/STAD.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Twist_Exome_Target  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/Twist_Exome_Target_hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovEsophagusMucosa  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-11NSD-1126-SM-5N9BQ.Esophagus_Mucosa.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId TGCT  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/TGCT.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Twist_Exome_Target2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/TwistExome21.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovEsophagusMuscularis  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1C475-0726-SM-73KVL.Esophagus_Muscularis.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId THCA  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/THCA.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId Twist_Exome_RefSeq_Targets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/exomeProbesets/Twist_Exome_RefSeq_targets_hg38.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovFallopianTube  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-OHPK-2326-SM-3MJH2.Fallopian_Tube.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId THYM  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/THYM.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovHeartAtrialAppendage  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-13S86-0326-SM-5SI6K.Heart_Atrial_Appendage.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId UCEC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/UCEC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovHeartLeftVentricle  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-NFK9-0926-SM-2HMJU.Heart_Left_Ventricle.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId UCS  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/UCS.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovKidneyCortex  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-13OVI-1126-SM-5KLZF.Kidney_Cortex.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId UVM  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/UVM.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovKidneyMedulla  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-T5JC-1626-SM-EZ6KW.Kidney_Medulla.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovLiver  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Y5LM-0426-SM-4VBRO.Liver.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovLung  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Y5V5-0826-SM-4VBQD.Lung.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovMinorSalivaryGland  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Y5LM-1826-SM-4VDT9.Minor_Salivary_Gland.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovMuscleSkeletal  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-NFK9-0626-SM-2HMIV.Muscle_Skeletal.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovNerveTibial  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-TML8-1626-SM-32QOO.Nerve_Tibial.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovOvary  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-ZVT2-0326-SM-5E44G.Ovary.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovPancreas  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1H1E6-0826-SM-9WG83.Pancreas.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovPituitary  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-Y111-2926-SM-4TT25.Pituitary.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovProstate  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-14DAR-1026-SM-73KV3.Prostate.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovSkinNotSunExposedSuprapubic  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1JN76-0626-SM-CKZOQ.Skin_Not_Sun_Exposed_Suprapubic.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovSkinSunExposedLowerleg  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1C475-1826-SM-73KWA.Skin_Sun_Exposed_Lower_leg.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovSmallIntestineTerminalIleum  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1PIEJ-1526-SM-E6CP8.Small_Intestine_Terminal_Ileum.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovSpleen  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-14PKU-0526-SM-6871A.Spleen.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovStomach  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-NFK9-1526-SM-3LK7B.Stomach.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovTestis  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1JKYN-1026-SM-CGQG4.Testis.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovThyroid  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1HSGN-0726-SM-A9G2F.Thyroid.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovUterus  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1MA7W-1526-SM-DHXKS.Uterus.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovVagina  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1IDJU-1026-SM-AHZ2U.Vagina.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexCovWholeBlood  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/cov/GTEX-1LG7Z-0005-SM-DKPQ6.Whole_Blood.RNAseq.bw
jbrowse add-track --out /Users/colin/ucscResults2 --trackId abSplice  https://hgdownload.soe.ucsc.edu/gbdb/hg38/abSplice/AbSplice.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId avada  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/avada.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoL2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/celltype.l2.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoL3  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/celltype.l3.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoPhase  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/Phase.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId bloodHaoTime  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/bloodHao/time.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cactus447way  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/cactus447way/hg38.cactus447way.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId chm13LiftOver  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/chm13LiftOver/hg38-chm13v2.ncbi-qnames.over.chain.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId clinvarSubLolly  https://hgdownload.soe.ucsc.edu/gbdb/hg38/clinvarSubLolly/clinvarSubLolly.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId colonWangCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/colonWang/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId colonWangDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/colonWang/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cortexVelmeshevCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cortexVelmeshev/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cortexVelmeshevDiagnosis  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cortexVelmeshev/diagnosis.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cortexVelmeshevDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cortexVelmeshev/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cortexVelmeshevSample  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cortexVelmeshev/sample.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cortexVelmeshevSex  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/cortexVelmeshev/sex.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cosmicMuts  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cosmic/cosmic.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cosmicRegions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cosmic/cosMutHg38V82.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId crisprAllTargets  https://hgdownload.soe.ucsc.edu/gbdb/hg38/crisprAll/crispr.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId decipher  https://hgdownload.soe.ucsc.edu/gbdb/hg38/decipher/decipherCnv.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddDel  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/del.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId dgvGold  https://hgdownload.soe.ucsc.edu/gbdb/hg38/dgv/dgvGold.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasAssay  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/Assay.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasExperiment  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/Experiment_batch.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasOrganCellLineage  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/Organ_cell_lineage.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasOrgan  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/Organ.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasRtGroup  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/RT_group.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId fetalGeneAtlasSex  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/fetalGeneAtlas/sex.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId genCC  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/genCC.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId interactions  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/interactions.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId geneReviews  https://hgdownload.soe.ucsc.edu/gbdb/hg38/geneReviews/geneReviews.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId gtexTranscExpr  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gtex/gtexTranscExpr.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasAgeGroup  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/age_group.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasCellTypes  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasRegion  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/region.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasSample  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/sample.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasSex  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/sex.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasSource  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/source.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasCellStates  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/cell_states.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId heartAtlasVersion  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/heartCellAtlas/version.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hgmd  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/hgmd.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hgnc  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hgnc/hgnc.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ileumWangCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/ileumWang/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId ileumWangDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/ileumWang/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId caddIns  https://hgdownload.soe.ucsc.edu/gbdb/hg38/cadd/ins.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId KICH  https://hgdownload.soe.ucsc.edu/gbdb/hg38/gdcCancer/KICH.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartBroadCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/broad_celltype.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartCompartment  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/compartment.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartDetailedCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartExperiment  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/Experiment.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId kidneyStewartProject  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/kidneyStewart/Project.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId liverMacParlandBroadCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/liverMacParland/BroadCellType.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId liverMacParlandCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/liverMacParland/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId liverMacParlandDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/liverMacParland/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lrgTranscriptAli  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lrgBigPsl.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020CellType10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020CellTypeFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020Compartment10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/compartment.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020CompartmentFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/compartment.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020DetailedCellType10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020DetailedCellTypeFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020Donor10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020DonorFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020GatingFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/gating.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020HalfDetailedCellType10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/half_merged.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020HalfDetailedFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/half_merged.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020LabelFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/label.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020Location10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/location.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020LocationFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/location.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020MagneticSelection10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/magnetic.selection.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020Organ10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/organ.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020OrganFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/organ.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020Sample10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/droplet/sample.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId lungTravaglini2020SampleFacs  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/lungTravaglini2020/facs/sample.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId mane  https://hgdownload.soe.ucsc.edu/gbdb/hg38/mane/mane.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId mastermind  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/mastermind.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId singleCellMerged  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/singleCellMerged/singleCellMerged.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId muscleDeMicheliCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/muscleDeMicheli/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId muscleDeMicheliSample  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/muscleDeMicheli/sample.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId orphadata  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/orphanet/orphadata.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pancreasBaronBatch  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/pancreasBaron/batch.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pancreasBaronCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/pancreasBaron/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pancreasBaronDetailedCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/pancreasBaron/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId pancreasBaronDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/pancreasBaron/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoCellType10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/10x/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoCellTypeSs2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/ss2/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoCellDetailed10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/10x/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoCellDetailedSs2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/ss2/detailed_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoLocation10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/10x/Location.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoLocationSs2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/ss2/Location.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoMatFet10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/10x/mom_child.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoMatFetSs2  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/ss2/mom_child.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId placentaVentoTormoStage10x  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/placentaVentoTormo/10x/Stage.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId rectumWangCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/rectumWang/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId rectumWangDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/rectumWang/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId skinSoleBoldoAge  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/skinSoleBoldo/age.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId skinSoleBoldoCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/skinSoleBoldo/cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId skinSoleBoldoAgeCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/skinSoleBoldo/age_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId skinSoleBoldoDonor  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/skinSoleBoldo/donor.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId tabulaSapiensFullDetails  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/tabulaSapiens/facet_detailed.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId tabulaSapiensTissueCellType  https://hgdownload.soe.ucsc.edu/gbdb/hg38/bbi/tabulaSapiens/tissue_cell_type.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId spMut  https://hgdownload.soe.ucsc.edu/gbdb/hg38/uniprot/unipMut.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId vistaEnhancersBb  https://hgdownload.soe.ucsc.edu/gbdb/hg38/vistaEnhancers/vistaEnhancers.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hprcInsertsV1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hprcArrV1/hprcInsertsV1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hprcDeletionsV1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hprcArrV1/hprcDeletionsV1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hprcArrInvBedV1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hprcArrV1/hprcArrInvV1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hprcArrDupBedV1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hprcArrV1/hprcArrDupV1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId hprcDoubleV1  https://hgdownload.soe.ucsc.edu/gbdb/hg38/hprcArrV1/hprcDoubleV1.bb
jbrowse add-track --out /Users/colin/ucscResults2 --trackId cactus241wayBM  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/cactus241way/cactus241way.bigMaf
